---
title: Centreer je uiterlijken
hero_image: images/banner.png
description: Centre your costumes
version: 4
listed: false
copyedit: false
last_tested: "2020-12-09"
steps:
  - 
    title: Centreer je uiterlijken
