---
title: Centriraj svoje kostime
hero_image: images/banner.png
description: Centriraj svoje kostime
version: 4
listed: false
copyedit: false
last_tested: "2020-12-09"
steps:
  - 
    title: Centriraj svoje kostime
