---
title: Kostüme zentrieren
hero_image: images/banner.png
description: Kostüme zentrieren
version: 4
listed: false
copyedit: false
last_tested: "2020-12-09"
steps:
  - 
    title: Kostüme zentrieren
