---
title: Centralize suas fantasias
hero_image: images/banner.png
description: Centralize suas fantasias
version: 4
listed: false
copyedit: false
last_tested: "2020-12-09"
steps:
  - title: Centralize suas fantasias
