---
title: Vycentrujte své kostýmy
hero_image: images/banner.png
description: Vycentrujte své kostýmy
version: 4
listed: false
copyedit: false
last_tested: "2020-12-09"
steps:
  - 
    title: Vycentrujte své kostýmy
