---
title: Centrer tes costumes
hero_image: images/banner.png
description: description réticule-scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-12-09"
steps:
  - 
    title: Centre your costumes
